### ISSUE TITLE
Lockout overturns are set upstairs

### ISSUE THREAD

**Issue by Tadukoo** [Tadukoo/CS481-Senior-Software#2]
If a manager overturns a lockout more than twice, a message will be sent to that mangers supervisor and so on up the chain of leadership. This can prevent managers from abusing their power to keep their subordinates working and opening up compliance issues.

**Comment by Dglispy** [comment]
Yes. Agree.

**Comment by Tadukoo** [comment]
Closing since we're not doing anything with it
